### PR TITLE
Add auto-reload support to logstash configuration file

### PR DESCRIPTION
**Pull request by davidt99**

### CODE REVIEW

**Comment by spujadas** [comment]
Good idea. Rather than having it in the `args` variable, could you move the option to the `LS_OPTS` variable?

**Comment by davidt99** [comment]
Done

**Comment by spujadas** [comment]
Cheers.

**Comment by spujadas** [comment]
Sorry, had to revert this one due to Logstash crashing (as reported in #32) when config files contain conditionals (which is the case in the default image), see https://github.com/elastic/logstash/issues/5014, https://github.com/elastic/logstash/issues/4968 — my mistake, didn't test the patch properly.

As this is supposed to have been fixed in Logstash 2.3.1, which was released a couple of hours ago, I'll upgrade the image and attempt to re-add the `--auto-reload` option (and test it properly!).

**Comment by davidt99** [comment]
I don't experiencing this issue, but I in the other hand, I don't use filebeat and the reason why I need to change the config.
I will try to look in to that in sunday.

**Comment by spujadas** [comment]
OK, that would explain.
Anyway, I've just upgraded Logstash in the image, tested it with `--auto-reload`, and it's running properly, so you can get the latest image (the build is in progress on Docker Hub, should be ready in a few minutes) and it should work fine.
If you do run some tests on Sunday and run into problems with this updated image, let me know.

**Pull request merged**
