### PR TITLE
When parsing cluster name from elasticsearch.yml, support nested yml format

### PR DESCRIPTION
**Pull request by anyat8**

### CODE REVIEW

**Comment by anyat8** [comment]
Hi!
In start.sh, when parsing cluster name from elasticsearch.yml, I added support for nested yml format, for example:

```
cluster:
    foo: bat
    name: my-cluster
```

**Comment by spujadas** [comment]
Hi, thanks for the PR and additional explanations (that regex is now quite a mouthful!), will do a few tests (esp. to check for non-regression) and merge.

**Comment by spujadas** [comment]
LGTM, thanks again!

**Comment by anyat8** [comment]
Great, thanks for the quick merge!

**Comment by spujadas** [comment]
Uh oh, I'm going to have to revert the merge and do something else: things were working on my machine, but it turns out that it was because of a bug in the outdated version of grep that I was using (and that you're using too apparently 😄).

I just realised that in the built image (which uses grep 2.25), the regex doesn't work at all, see http://stackoverflow.com/questions/37618736/grep-unescaped-or-not-supported-with-pz for a discussion of the issue in the latest version of grep (as from 2.24, released in March).
Unfortunately, none of the workarounds suggested in the post on SO appear to work.

As parsing YAML (especially multiline YAML) with grep/sed/awk/etc. is [hackish](http://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script), and I don't really want to overload the image with pip to install [shyaml](https://github.com/0k/shyaml) or node/npm to install [YAML-CLI](https://www.pandastrike.com/open-source/yaml-cli/), I'm going to use Elasticsearch's API to request the name of the cluster instead (i.e. `curl localhost:9200/_cat/health?h=cluster`).

**Comment by anyat8** [comment]
Ok, sounds like a good solution!

**Pull request merged**
