### PR TITLE
Update 5615

### PR DESCRIPTION
**Pull request by selman**
updated 5.6.15 & synced to [master](https://github.com/spujadas/elk-docker/tree/master).

### CODE REVIEW

**Comment by spujadas** [comment]
PR much appreciated as always, thanks!

**Comment by selman** [comment]
hi @spujadas, may u build 5615 image? I think u wrongly rebuild latest https://hub.docker.com/r/sebp/elk/tags :laughing:

**Comment by spujadas** [comment]
Actually, there's an ongoing problem on Docker Hub which makes it impossible to rebuild a specific tag :sweat_smile:…
I hope it gets solved soon because I haven't been able to build 661 (had to resort to building latest instead) and 5615.

**Comment by selman** [comment]
ok thanks a lot @spujadas

**Comment by spujadas** [comment]
Finally managed to trigger the build, the 5615 image should now be available.

**Pull request merged**
