### PR TITLE
ARM64 enablement

### PR DESCRIPTION
**Pull request by mgazzin**
Dear @spujadas , I have made a change to your Dockerfile that allows to build this image in ARM64 systems.
I have tested it on my raspberry pi 4 and in my x86_64 system.
I hope you can review it and possibly add to your repository.
The docker build comment is documented in README.md file.

Kindly let me know.
Thanks.
Cheers

### CODE REVIEW

**Comment by spujadas** [comment]
Great idea, thanks for the PR!
I'll work it into the repo over the weekend, first I need to work out how to multi-arch-enable the build process. 😄

**Comment by mgazzin** [comment]
Thanks @spujadas . Please let me know if you have interesting findings.

**Comment by spujadas** [comment]
This whole multi-arch thing looked a tad too experimental for my liking, so I just merged your PR (almost*) as is.
(* moved the documentation to the main doc and added a note on the OSS versions not being supported on ARM64)

Thanks again for you PR, much appreciated.

Note to self: [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/); [Docker multi-arch example](https://github.com/ckulka/docker-multi-arch-example).

**Comment by mgazzin** [comment]
Ok! Thank you very much @spujadas .
Cheers!

**Pull request merged**
